import { ResumeSchema } from "types/resume";

export const resumeSchema: ResumeSchema = {
  work: [
    {
      companyName: "Frontiers",
      title: "Technical Lead (Design System)",
      location: "Zurich, Switzerland",
      startDate: "Feb 2023",
      endDate: "Present",
      description: [
        "Led a team of 6 developers in creating the frontend architecture for the component library based on the Brink Design System. Utilized technologies such as Lerna/NX Monorepo, Vue 3, TypeScript, SCSS (BEM), Cypress, and Percy. Published and distributed the library to other teams via NPM, following semantic versioning and conventional commits.",
        "Collaborated closely with the Product and Design teams to identify and build UX patterns. Developed a documentation platform using Storybook to showcase and document the component library, and seamlessly integrated it with our ZeroHeight platform.",
        "Acted as the Accessibility Expert for the team, ensuring comprehensive testing and audits for usability. Ensured compatibility for diverse user needs, including support for keyboard-only users, screen readers, and assistive technologies.",
        "Played a key role in screening and interviewing candidates for most of the Frontend roles at Frontiers. Successfully identified and hired suitable candidates to strengthen the Design System team. Additionally, provided oversight in hiring frontend engineers for some of Frontiers' outsourced teams.",
        "Worked in collaboration with other Technical Leads and the Software Architects across the company to strategize and plan the adoption of the new design system across multiple platforms and products.",
      ],
    },
    {
      companyName: "Meta / Facebook",
      title: "Frontend Engineer",
      location: "Zurich, Switzerland",
      startDate: "Jun 2022",
      endDate: "Feb 2023",
      isContract: true,
      description: [
        "Consulted for the Mapillary team, a startup acquired by Meta, to facilitate a smooth transition of their platforms and infrastructure into the Meta web ecosystem. Reviewed previous Meta acquisitions and engaged with key stakeholders to devise integration processes.",
        "Collaborated with the Mapillary team to identify optimal migration solutions, providing them with a range of options for gradually transitioning their software and products.",
        "Worked closely with the Design System Teams at Facebook and Instagram to explore possibilities for supporting an independent Design System/Component Library tailored to the Mapillary product line. Investigated the creation of a Headless system based on Facebook's existing component library.",
        "Took the lead in rewriting the Mapillary website, migrating it from Next.js to the Facebook CMS. This migration resulted in significant improvements to key performance metrics, with Accessibility scores improving by 36%, Performance by 17%, and SEO by 25%. Core Web Vitals also saw significant enhancements, including a 20% reduction in FCP and a 60% reduction in LCP.",
        "Implemented comprehensive internationalization (i18n) support for the Mapillary web apps (Angular, TypeScript), enabling localization in 24 different languages.",
      ],
    },
    {
      companyName: "Tundra",
      title: "Senior Frontend Engineer",
      location: "Zurich, Switzerland",
      startDate: "Nov 2021",
      endDate: "Jun 2022",
      description: [
        "Led the migration of Tundra.com's e-commerce platform from a client-side to a hybrid rendering model using Next.js. This transition resulted in a significant improvement of approximately 20-40% across all Core Web Vitals metrics. In addition, played a pivotal role in promoting Next.js adoption across frontend teams through workshops, demos, and pair programming.",
        "Designed the authentication strategy for WholesaleCoop.com, implementing improved web security measures. Developed the entire UI authentication flow on WholesaleCoop.com.",
        "Spearheaded the adoption of NX for the new WholeSaleCoop product within the Frontend team. Successfully set up the integration between NX and our CI/CD pipeline in CircleCI. This implementation led to a substantial improvement in CI execution time, leveraging the NX Graph, resulting in faster PR to deployment times.",
      ],
    },
    {
      companyName: "tray",
      title: "Senior Frontend Engineer",
      location: "Remote",
      startDate: "Jan 2021",
      endDate: "Oct 2021",
      description: [
        "Migrated the entire Tray Documentation platform from Gatsby to Next.js (React, TypeScript, Node.js). Built a custom compiler integrated within a new Next.js application for the creation of interactive pages based on markdown files generated by our technical writers. The compiler provided assistance and enforced stylistic conventions on the writers, transforming the files into React pages using MDX processing.",
      ],
    },
    {
      companyName: "OVO",
      title: "Frontend Engineer",
      location: "London, United Kingdom",
      startDate: "June 2020",
      endDate: "Jan 2021",
      description: [
        "Built an interactive map for the Web (React, TypeScript, RxJS, Redux), Android, and iOS (React Native) utilizing Mapbox and React Map GL. Created prototypes for each SDK provider (Google Maps, Mapbox, Leaflet) to evaluate performance and cost-effectiveness in relation to users' traffic. This ensured the adoption of a solution that delivered optimal performance and cost efficiency.",
      ],
    },
    {
      companyName: "Noble",
      title: "Frontend Engineer",
      location: "London, United Kingdom",
      startDate: "Jun 2019",
      endDate: "Feb 2020",
      description: [
        "Worked on Noble Vision, a Dashboard that allows analysts to view real-time threats within their network. Transitioned the application from a native desktop application built in Electron, to a web-based solution in React, Redux, TypeScript and GraphQL.",
      ],
    },
    {
      companyName: "Hackney Council",
      title: "Software Developer",
      location: "London, United Kingdom",
      startDate: "Sep 2016",
      endDate: "Jun 2019",
      description: [
        "Hired as a self-thought Software Developer. Built web features using Angular, TypeScript, C# and .NET Core 2.1.",
      ],
    },
  ],
};
